import { useCallback, useMemo, useState } from "react";
import { LabRecap, LabSection } from "@/components/lab";
import { useT } from "@/i18n";
import {
  ALPHA_DEFAULT,
  MU0_DEFAULT,
  MU1_DEFAULT,
  N_DEFAULT,
  SIGMA_DEFAULT,
  TEST_TYPE_DEFAULT,
  evaluate,
  type Params,
} from "./engine";
import { AlphaStage } from "./components/AlphaStage";
import { BetaStage } from "./components/BetaStage";
import { HypothesisChallenge } from "./components/HypothesisChallenge";
import { SampleSizeStage } from "./components/SampleSizeStage";
import { SeparationStage } from "./components/SeparationStage";

/**
 * Hypothesis Testing.
 *
 * One idea: **you do not get to be wrong less often, only to choose which way
 * you are wrong.**
 *
 * ## The order
 *
 * Two curves and a slider, before anything is named (1). Then the line that
 * splits them, and what putting it somewhere costs under H0 (2). Then the
 * other error, the one that lives under H1, and the direction you were looking
 * in (3). Then the only lever that improves both at once (4). Then two tasks
 * (5).
 *
 * ## One state, one calculation
 *
 * Sections 1 to 4 share a single `Params`, and each renders `evaluate()` of
 * it. Moving mu1 in section 1 moves the beta shading in section 3, because
 * they are the same model — not four widgets that happen to agree.
 *
 * ## Provenance
 *
 * The mathematics is a port of `Kuramsal Hipotez Testleri Simülasyonu.py`.
 * `engine.test.ts` checks every equation against reference values generated by
 * running that implementation's own functions under SciPy.
 */
export default function HypothesisTesting() {
  const t = useT();
  const copy = t.labs["hypothesis-testing"];

  const [params, setParams] = useState<Params>({
    mu0: MU0_DEFAULT,
    mu1: MU1_DEFAULT,
    sigma: SIGMA_DEFAULT,
    alpha: ALPHA_DEFAULT,
    n: N_DEFAULT,
    testType: TEST_TYPE_DEFAULT,
  });

  const update = useCallback(
    (patch: Partial<Params>) => setParams((current) => ({ ...current, ...patch })),
    [],
  );

  const result = useMemo(() => evaluate(params), [params]);

  return (
    <div className="space-y-20 md:space-y-28">
      {/* 1 — two curves, and nothing named. */}
      <section aria-labelledby="ht-separation-heading">
        <h2 id="ht-separation-heading" className="sr-only">
          {copy.separation.title}
        </h2>
        <p className="mb-6 max-w-prose text-body-lg text-fg">{copy.separation.question}</p>
        <SeparationStage result={result} onChange={update} />
      </section>

      {/* 2 — where the line goes, and what it costs under H0. */}
      <LabSection
        kicker={copy.alphaSection.kicker}
        title={copy.alphaSection.title}
        lede={copy.alphaSection.lede}
      >
        <AlphaStage result={result} onChange={update} />
      </LabSection>

      {/* 3 — the error that lives under H1. */}
      <LabSection
        kicker={copy.betaSection.kicker}
        title={copy.betaSection.title}
        lede={copy.betaSection.lede}
      >
        <BetaStage result={result} onChange={update} />
      </LabSection>

      {/* 4 — the one lever that helps both. */}
      <LabSection
        kicker={copy.sampleSection.kicker}
        title={copy.sampleSection.title}
        lede={copy.sampleSection.lede}
      >
        <SampleSizeStage result={result} onChange={update} />
      </LabSection>

      {/* 5 — now hit a number. */}
      <LabSection
        kicker={copy.challenge.kicker}
        title={copy.challenge.title}
        lede={copy.challenge.lede}
      >
        <HypothesisChallenge />
        <p className="mt-8 max-w-prose text-body-sm text-fg-faint">{copy.scope}</p>
      </LabSection>

      <LabRecap lessons={copy.recap.lessons} footer={copy.recap.footer} />
    </div>
  );
}
